### ISSUE TITLE
Error when connecting to server

### ISSUE THREAD

**Issue by iCesenberk** [ALIILAPRO/warp-plus-cloudflare#1]
![eroor](https://user-images.githubusercontent.com/60349856/83039059-e0b11a00-a067-11ea-87f7-28889fe38a87.PNG)

**Comment by husseinaltaaf** [comment]
Well issue still here!

**Comment by ALIILAPRO** [comment]
Fixed, check again.

**Comment by iCesenberk** [comment]
i'm currently using centos 7 with python 3.6 and 3.7 installed still got this error 
![error python 3 6](https://user-images.githubusercontent.com/60349856/83107715-eef34a80-a0e8-11ea-916c-f56b2b7280c2.PNG)
![error python 3 7](https://user-images.githubusercontent.com/60349856/83107818-16e2ae00-a0e9-11ea-943d-6534c8a1eb8d.PNG)
