### ISSUE TITLE
Server Fixed Again

### ISSUE THREAD

**Issue by SamOO-7** [ALIILAPRO/warp-plus-cloudflare#10]
CF fixed server again @ALIILAPRO

**Comment by shubzzz3** [comment]
Same problem again this day too.Please fix it.

**Comment by DeicPro** [comment]
Fixed here https://github.com/ALIILAPRO/warp-plus-cloudflare/pull/9

**Comment by SamOO-7** [comment]
> fixed

Awesome @ALIILAPRO @DeicPro :)
