### ISSUE TITLE
Request for Process to Fix server connection

### ISSUE THREAD

**Issue by camlogical** [ALIILAPRO/warp-plus-cloudflare#13]
Hello sir!!! Thank you for your great tool.
If can I hope you kindly show the trick to Fix server connection by myself?
How you get this?

		install_id = genString(22)
		body = {"key": "{}=".format(genString(43)),
				"install_id": install_id,
				"fcm_token": "{}:APA91b{}".format(install_id, genString(134)),
				"referrer": referrer,
				"warp_enabled": False,
				"tos": datetime.datetime.now().isoformat()[:-3] + "+02:00",
				"type": "Android",
				"locale": "es_ES"}

**Comment by DeicPro** [comment]
I got this seeing app request doing a new installation
