### ISSUE TITLE
Problem using the script on linux.

### ISSUE THREAD

**Issue by ErikEBZ** [ALIILAPRO/warp-plus-cloudflare#14]
Your script is amazing!, i'm using it on repl.run.

But i would like to run it locally, when i download the script and run it with python3.8.2, i insert my ID but the script freezes.
I tried to fix it but i couldn't.
Any idea on what could be the problem?

**Comment by ALIILAPRO** [comment]
Hi, check your internet connection or delete Python completely and reinstall.
