### ISSUE TITLE
Proxy support for python script

### ISSUE THREAD

**Issue by mishailovic** [ALIILAPRO/warp-plus-cloudflare#16]
You can use the https://proxyscrape.com/ api for getting them

**Comment by ALIILAPRO** [comment]
Hi thanks, I used this api in gui version.

**Comment by mishailovic** [comment]
My advice, modify the python script, it is much better than the windows program, because python is cross-platform. It would be nice to add proxies and randomization to the user agent.  It is necessary to make cloudflare not notice the cheat

**Comment by senhan07** [comment]
@ALIILAPRO can you add proxy features on python script??. Because i can run on headless server and run it 24/7. I already stressed out trying modify the script but no result :(

**Comment by mishailovic** [comment]
> @ALIILAPRO can you add proxy features on python script??. Because i can run on headless server and run it 24/7. I already stressed out trying modify the script but no result :(

I made a python script with proxy support
https://github.com/mishailovic/warpy/
