### ISSUE TITLE
Error when connecting to server.

### ISSUE THREAD

**Issue by shubzzz3** [ALIILAPRO/warp-plus-cloudflare#18]
![Screenshot 2020-08-16 at 11 27 44 AM](https://user-images.githubusercontent.com/61401662/90327657-82833b80-dfb3-11ea-95e3-bcc0ce4ffbd9.png)

Please update.
Thank you.

**Comment by XOKP** [comment]
I have no issue connecting here.

**Comment by shubzzz3** [comment]
Working now.
Thanks
