### ISSUE TITLE
Windows GUI

### ISSUE THREAD

**Issue by oleteacher** [ALIILAPRO/warp-plus-cloudflare#19]
First, what a great project! This is just the type of project we love to explore in classroom 👍 

Having senior moment. Could you explain how to interface the Win GUI with the script?

Assuming that you install warp-plus-cloudflare on windows machine, then run GUI? Tried this method and not working. Discovers 1900+ proxies but all are bad.

The "wp-plus(version4.0)" works fine on machine, tested and works great.

Thank you again for the project!

**Comment by chuyendoithuong** [comment]
same error

**Comment by oleteacher** [comment]
Have a feeling my question is considered stupid. Just everyone remember: the only stupid question is one you already know and ask the answer too...

**Comment by ALIILAPRO** [comment]
> 
> 
> Have a feeling my question is considered stupid. Just everyone remember: the only stupid question is one you already know and ask the answer too...

Hi, this app is currently broken. I need time to update this project. please be patient. thank you

**Comment by ALIILAPRO** [comment]
> 
> 
> same error



> 
> 
> Have a feeling my question is considered stupid. Just everyone remember: the only stupid question is one you already know and ask the answer too...

Follow my channel on Telegram to be informed of updates. https://t.me/source_pro

**Comment by oleteacher** [comment]
> Hi, this app is currently broken. I need time to update this project. please be patient. thank you

No problem, not rushing you by any means. Did not know it was broken, only assumed I did not know how to use and reason I waited 7 days to reply a second time :)

**Comment by ALIILAPRO** [comment]
> 
> 
> same error



> 
> 
> > Hi, this app is currently broken. I need time to update this project. please be patient. thank you
> 
> No problem, not rushing you by any means. Did not know it was broken, only assumed I did not know how to use and reason I waited 7 days to reply a second time :)

fixed. download gui-v2 https://github.com/ALIILAPRO/warp-plus-cloudflare/releases/tag/gui-v2

**Comment by oleteacher** [comment]
Thank you for taking time to fix, works great!
