### ISSUE TITLE
Proxy List

### ISSUE THREAD

**Issue by oleteacher** [ALIILAPRO/warp-plus-cloudflare#21]
Seems the GUI is broken again. Get error about SSL when trying to load proxy.

Is there a place to get a compatible proxy list that is loaded locally?

Thanks!

**Comment by ALIILAPRO** [comment]
Hi, fixed.
https://github.com/ALIILAPRO/warp-plus-cloudflare/releases/tag/gui-v2.1

**Comment by oleteacher** [comment]
Thank you! Was still wondering how to get a proxy list to load locally?

**Comment by ALIILAPRO** [comment]
proxyscrape.com
