### ISSUE TITLE
Add support for WARP+ PC client?

### ISSUE THREAD

**Issue by MikuDroid** [ALIILAPRO/warp-plus-cloudflare#22]
Seems like the key from mobile and PC client is different?

on mobile it's : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
and on PC it's : xxxxxxxx-xxxxxxxx-xxxxxxxx

**Comment by yogathanh99** [comment]
You can use the client id of mobile to get data and use key of this account add to PC. If you do this, you can get WARP+
