### ISSUE TITLE
GB is not increased after boost

### ISSUE THREAD

**Issue by heroes1412** [ALIILAPRO/warp-plus-cloudflare#23]
i trie python script or windows app to boost my id, but it still show 0GB :). does your script work now?

**Comment by rizqiimani** [comment]
me too, i got notification on my Android that I got 1GB cause someone accepted referral code, but still my Warp+ is not added to the account

**Comment by TanjimReza** [comment]
Reset Encryption Key & then it will show data.

**Comment by HrithikAnchaliya** [comment]
How to reset the encryption ..

**Comment by mehenuf** [comment]
Facing the same problem tried Reseting Security keys but still not working.

**Comment by rizqiimani** [comment]
After resetting encryption key a couple of times, close the app (or quit it if you're using Mac like me) then open the app again to see results. I used both license key on my Mac and Android phone, they have different Warp+ ID but will share the same quota. So I've been running the script from my Mac and got the quota both on my Mac and Android Phone.

**Comment by TanjimReza** [comment]
So, fixed?

**Comment by minlaxz** [comment]
> Reset Encryption Key & then it will show data.

Yes, it works.

**Comment by TanjimReza** [comment]
Close the issue

**Comment by littlesudip** [comment]
> Close the issue

Hello Brother, Is this scirpt still working for wrap+ ?  I've tried so many times but it does not add any GB on WARP+ Referral reward.
I've also reset Encryption Key and force closed that app. but still no luck. please help me out.

**Comment by HrithikAnchaliya** [comment]
@littlesudip While running the script did it hit any bad request, or maybe re-check the ID used in the script.

**Comment by SylveonBottle** [comment]
Still works.
LMAO HAHAHAHA this project is amazing

**Comment by duongtuan303030** [comment]
> Reset Encryption Key & then it will show data.

it not work

**Comment by Z3r4t05** [comment]
> > Reset Encryption Key & then it will show data.
> 
> it not work
yeah same for me

**Comment by malikshi** [comment]
Yes it's not works.  I boosted 3 key but still 0MB

**Comment by minlaxz** [comment]
Make sure you’ve copied the right one **Client ID** in the app’s Settings/Advanced/Diagnostics/Client Configurations/Client ID
_It should be `8-4-4-4-12` characters_

The script is not producing an error, if you wrongly supplied with **Security key**, or any _other string_. That’s why you run the script and nothing happens.

If you would like to test I have implemented [this](https://mvtvso.deta.dev/) based on the logic.

**Comment by HrithikAnchaliya** [comment]
Yep, still works. If it is not working for you re-check the steps.

**Comment by malikshi** [comment]
The account must from mobile phone and it's work but when creating account from pc/linux server it's doesn't work.

**Comment by Cortana-117** [comment]
Hi,
I have tried everything suggested here and in the home page, still no GB is increased, can someone help please?

I have latest version of official app installed on Android 11.

I tried resetting security keys, resetting all settings and then adding the same key to the app again, force stopping app etc. still 0 GB

**Comment by Z3r4t05** [comment]
> Make sure you’ve copied the right one **Client ID** in the app’s Settings/Advanced/Diagnostics/Client Configurations/Client ID _It should be `8-4-4-4-12` characters_
> 
> The script is not producing an error, if you wrongly supplied with **Security key**, or any _other string_. That’s why you run the script and nothing happens.
> 
> If you would like to test I have implemented [this](https://mvtvso.deta.dev/) based on the logic.

tks, it works.
