### ISSUE TITLE
Code get bad errors

### ISSUE THREAD

**Issue by hishirooo** [ALIILAPRO/warp-plus-cloudflare#24]
Thank for sharing code. But now i using it having many bad errors. Hope you can fix it ? 
Thanks.
```
[:)] 41 GB has been successfully added to your account.
[#] Total: 41 Good 95 Bad
[*] After 5 seconds, a new request will be sent.
```

**Comment by rdxshubham** [comment]
Yes, so, when you are spamming the server on the high rate, you will get the bad request. To prevent this, increase the sleep time for each request or update the line no 85 with `time.sleep(random.randrange(100,150))` which will do the sleep between 100 seconds to 150 seconds. This will be help you from bad requests.

**Comment by minlaxz** [comment]
Suggest : @hishirooo if you don't have time to wait for **free** GB, setup a webhook https://mvtvso.deta.dev/get?uid=`your_8_4_4_4_12` uid with IFTTT or Zapier or smth. But do not spam the server on the high rate!
