### ISSUE TITLE
WARP+ was not increase

### ISSUE THREAD

**Issue by saiwaihlyanhtun** [ALIILAPRO/warp-plus-cloudflare#25]
I run the script and it's working fine. I saw the notification that I got 1 GB more. But it's not really added in 1.1.1.1 app. Please fix that.

**Comment by PhAnToM-sOuL** [comment]
.

**Comment by talachanmon** [comment]
You need to go advance/ connection option and reset security keys  close and open again

**Comment by saiwaihlyanhtun** [comment]
> You need to go advance/ connection option and reset security keys close and open again

Got it. Thanks a lot
