### ISSUE TITLE
Stop didn't Work at GUI

### ISSUE THREAD

**Issue by h2kyaw** [ALIILAPRO/warp-plus-cloudflare#31]
Hello, I think and I faced the problem that can't stop at GUI version.

Kindly fix that issues please. Stop button doesn't Important but I wonderful at functionable as I see.

Thanks.

**Comment by ALIILAPRO** [comment]
https://github.com/ALIILAPRO/warp-plus-cloudflare/releases/download/gui-v2.2.1/wp-plus.GUI.zip
