### ISSUE TITLE
No an issue but a feature request

### ISSUE THREAD

**Issue by wes1993** [ALIILAPRO/warp-plus-cloudflare#33]
Hello, 
this script works reall well but could you add the proxy functionality also in the cli script?

Thanks a lot
Stefano

**Comment by burritosoftware** [comment]
@ALIILAPRO The CLI is lacking in the proxylist feature and I would like to run this on a linux server, please consider adding it :)

**Comment by loci456** [comment]
@burritosoftware 
Here's a small modification of the python script to add automatic proxying to each request.
To work, you need to install two packages via pip :
`pip install beautifulsoup4 `
`pip install lxml`
download the modified script : [wp-plus.zip](https://github.com/ALIILAPRO/warp-plus-cloudflare/files/6846451/wp-plus.zip)
P.S I am still thinking of a simpler and more user-friendly function to get a list of proxies.
