### ISSUE TITLE
 warp-plus-cloudflare

### ISSUE THREAD

**Issue by baba2580** [ALIILAPRO/warp-plus-cloudflare#4]
Error when connecting to server
![A](https://user-images.githubusercontent.com/23245020/83076334-f7209b00-a092-11ea-93da-ad63c7011268.jpg)

**Comment by ALIILAPRO** [comment]
> 
> 
> Error when connecting to server
> ![A](https://user-images.githubusercontent.com/23245020/83076334-f7209b00-a092-11ea-93da-ad63c7011268.jpg)

uninstall python on your system. install this version https://www.python.org/ftp/python/3.6.0/python-3.6.0-amd64.exe

**Comment by baba2580** [comment]
previous it work on 3.8 python then now why to downgrade

**Comment by baba2580** [comment]
previously it works on 3.8 python now why to downgrade 3.6.0

**Comment by ALIILAPRO** [comment]
> 
> 
> previous it work on 3.8 python then now why to downgrade

Due to ssl error. or you can use app http://bayanbox.ir/download/6017786215883517166/wp-plus.zip

**Comment by baba2580** [comment]
Thanks it working
