### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Uranite** [ALIILAPRO/warp-plus-cloudflare#46]
![image](https://user-images.githubusercontent.com/62639703/147853538-6ea26332-cbf5-4117-8d0a-6bfd265bbb79.png)
edit: also i forgot to say that this happened after you press get proxylist

**Comment by Pushkin31** [comment]
I support this. I wrote to the developer in Telegram about it - he said he would take a look at it.

Ali B, [31.12.2021 12:27]
Hi, i'll check.

**Comment by mitchellsantner** [comment]
i have also same error

**Comment by supunsathsara** [comment]
**I'm getting the same error..** :-(
- does anyone know a way to get a proxy list manually that works with this program....??

**Comment by supunsathsara** [comment]
@Pushkin31 @mitchellsantner @Uranite Try using the python script instead of the GUI.. Worked for me..
Also there is pull request { #47  } that fixed the issue I recommend to check that if you really want the GUI version.

**Comment by Pushkin31** [comment]
@supunsathsara Hello. Yes, I am using the version without gui, but with the threads specified.
As a solution - in the program specify the file in the proxy list and replace the file with the [link](https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all)
Windows Explorer will save the proxy file to a temporary folder, and the program will use it.

**Comment by supunsathsara** [comment]
> @supunsathsara Hello. Yes, I am using the version without gui, but with the threads specified. As a solution - in the program specify the file in the proxy list and replace the file with the [link](https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all) Windows Explorer will save the proxy file to a temporary folder, and the program will use it.
@Pushkin31 
Thanks man <3

**Comment by Uranite** [comment]
seems to be fixed so im closing this
