### ISSUE TITLE
After Added GB In WARP+ (ANDROID)  WARP+ didn't work

### ISSUE THREAD

**Issue by Bhadu29** [ALIILAPRO/warp-plus-cloudflare#48]
![Screenshot_20220125-131406_1111](https://user-images.githubusercontent.com/66292062/151106024-673c3e5b-04dc-4155-8688-6910824099c4.jpg)

After adding GB in WARP+  when i am try to use it it showing " Updating Connection Info...".

I uninstall the app and retry to fix it but it still have same issues.

So please help me

**Comment by supunsathsara** [comment]
Maybe try resetting the license key from the settings menu & run this program again..

**Comment by Pushkin31** [comment]
@Bhadu29 Apparently your operator blocks this dns.
In connection options set custom endpoint.
I am from Russia and I set 162.159.193.8:2408
I did it following the advice of the forum 4pda, which one will suit you and how you find it - I have no idea :(
