### ISSUE TITLE
Termux not connecting to the server

### ISSUE THREAD

**Issue by DankestFke** [ALIILAPRO/warp-plus-cloudflare#50]
![ScreenCrop-20220315-094137](https://user-images.githubusercontent.com/62785913/158289142-1e09cffd-fd50-4ee0-a627-2d2e17ed4b65.jpeg)

**Comment by DankestFke** [comment]
And still to be continue with Bad Totals

**Comment by aaartech** [comment]
i'm facing the same issue

**Comment by nb-duong** [comment]
I have the same problem

**Comment by SwiftyPop** [comment]
I also have the same issue on GUI

**Comment by aaartech** [comment]
guys try this one :
search for proxy list on GitHub
copy the list and paste in a txt file and save it
then try to load that list on GUI version
it must work! i got 100GB from refer

**Comment by SwiftyPop** [comment]
@aaartech can you give me that proxylist you used? I tried mine and I still get hundred of bads

**Comment by aaartech** [comment]
@SwiftyPop 
https://github.com/TheSpeedX/PROXY-List/blob/master/http.txt
https://github.com/clarketm/proxy-list/blob/master/proxy-list-raw.txt
https://github.com/jetkai/proxy-list/blob/main/online-proxies/txt/proxies-http%2Bhttps.txt

**Comment by SwiftyPop** [comment]
@aaartech Tysm it work! Appreciate it!!

**Comment by TheCaduceus** [comment]
> ![ScreenCrop-20220315-094137](https://user-images.githubusercontent.com/62785913/158289142-1e09cffd-fd50-4ee0-a627-2d2e17ed4b65.jpeg)

This problem already resolved here: https://github.com/TheCaduceus/WARP-UNLIMITED-ADVANCED
