### ISSUE TITLE
"The underlying connection was closed: an unexpected error occurred on send"

### ISSUE THREAD

**Issue by Swift4895** [ALIILAPRO/warp-plus-cloudflare#54]
Every time I click on the proxy list (the green button with '_s1_' text on it) it says 
**"The underlying connection was closed: an unexpected error occurred on send"**
I've been trying the same thing over and over again, tried **redownloading it** but it wouldn't budge.
Here is the screenshot of it:
![image_2022-07-03_123438655](https://user-images.githubusercontent.com/103976380/177033875-2741f3c3-8dfc-4109-8f0c-1daa387527eb.png)
Hope this issue fixes soon. It use to work earlier but it wouldn't work now.
Thanks.

**Comment by ALIILAPRO** [comment]
use this version. https://github.com/ALIILAPRO/warp-plus-cloudflare/releases/download/gui-v2.2.1/wp-plus.GUI.zip
