### ISSUE TITLE
This script no longer works

### ISSUE THREAD

**Issue by erbanku** [ALIILAPRO/warp-plus-cloudflare#57]
This script and GUI app shows the operation successfully, but actually it is not, it seems this script blocked by Cloudflare.

**Comment by SwiftyPop** [comment]
Thanks to @TheCaduceus , you can try this [one](https://github.com/TheCaduceus/WARP-UNLIMITED-ADVANCED#%EF%B8%8F-how-to-use-).

**Comment by erbanku** [comment]
> Thanks to @TheCaduceus , you can try this [one](https://github.com/TheCaduceus/WARP-UNLIMITED-ADVANCED#%EF%B8%8F-how-to-use-).

**I am going to try, thanks.**
