### ISSUE TITLE
Clodflare fixed ?

### ISSUE THREAD

**Issue by Kingsmanvn-Official** [ALIILAPRO/warp-plus-cloudflare#61]
i have successfully run the script 221 times but warp doesn't add
![Screenshot_2022-11-04-18-20-12-015-edit_com android chrome](https://user-images.githubusercontent.com/94727017/199961044-cb08383f-5727-4330-b025-90c2d652c85e.jpg)
![Screenshot_2022-11-04-18-21-25-135-edit_com cloudflare onedotonedotonedotone](https://user-images.githubusercontent.com/94727017/199961072-e9a3fc0b-12b3-450c-8f29-61faee87076f.jpg)

**Comment by ALIILAPRO** [comment]
> i have successfully run the script 221 times but warp doesn't add ![Screenshot_2022-11-04-18-20-12-015-edit_com android chrome](https://user-images.githubusercontent.com/94727017/199961044-cb08383f-5727-4330-b025-90c2d652c85e.jpg) ![Screenshot_2022-11-04-18-21-25-135-edit_com cloudflare onedotonedotonedotone](https://user-images.githubusercontent.com/94727017/199961072-e9a3fc0b-12b3-450c-8f29-61faee87076f.jpg)

just go to advance / connection option and reset security keys, close and open again.

**Comment by Kingsmanvn-Official** [comment]
> 

no working

**Comment by ALIILAPRO** [comment]
> > 
> 
> no working

you sure u using warp id? 
https://github.com/ALIILAPRO/warp-plus-cloudflare#-how-to-get-the-warp-id
