### ISSUE TITLE
Proxy connection errors

### ISSUE THREAD

**Issue by ik4ito** [ALIILAPRO/warp-plus-cloudflare#62]
Title^
Doesnt let me grab any proxylists

**Comment by ALIILAPRO** [comment]
> Title^ Doesnt let me grab any proxylists

tell me more.

**Comment by ik4ito** [comment]
> > Title^ Doesnt let me grab any proxylists
> 
> tell me more.

Never mind, it was solved by using a VPN. Seems like the source of the proxies was blocked in my country, go figure :^)

**Comment by ALIILAPRO** [comment]
> > > Title^ Doesnt let me grab any proxylists
> > 
> > 
> > tell me more.
> 
> Never mind, it was solved by using a VPN. Seems like the source of the proxies was blocked in my country, go figure :^)

ahhhhhha
