### ISSUE TITLE
Getting this error. Everytime i run the script ni my macBook Pro

### ISSUE THREAD

**Issue by shubzzz3** [ALIILAPRO/warp-plus-cloudflare#8]
Last login: Sat May 30 08:34:45 on ttys000
nimbus@MacBook-Pro ~ % python3 wp-plus.py
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't open file 'wp-plus.py': [Errno 2] No such file or directory
nimbus@MacBook-Pro ~ % cd /Users/nimbus/Downloads/warp-plus-cloudflare-master
nimbus@MacBook-Pro warp-plus-cloudflare-master % cd /Users/nimbus/Downloads/warp-plus-cloudflare-master
nimbus@MacBook-Pro warp-plus-cloudflare-master % python3 wp-plus.py
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `title WARP-PLUS-CLOUDFLARE By ALIILAPRO (version 3.0.0)'

      _______ _      __________________       _______ _______ _______ _______
     (  ___  | \     \__   __|__   __( \     (  ___  |  ____ |  ____ |  ___  )
     | (   ) | (        ) (     ) (  | (     | (   ) | (    )| (    )| (   ) |
     | (___) | |        | |     | |  | |     | (___) | (____)| (____)| |   | |
     |  ___  | |        | |     | |  | |     |  ___  |  _____)     __) |   | |
     | (   ) | |        | |     | |  | |     | (   ) | (     | (\ (  | |   | |
     | )   ( | (____/\__) (_____) (__| (____/\ )   ( | )     | ) \ \_| (___) |
     |/     \(_______|_______|_______(_______//     \|/      |/   \__(_______)

[+] ABOUT SCRIPT:
[-] With this script, you can getting unlimited GB on Warp+.
[-] Version: 3.0.0
--------
[+] THIS SCRIPT CODDED BY ALIILAPRO
[-] SITE: aliilapro.github.io
[-] TELEGRAM: aliilapro
--------
[#] Enter the WARP+ ID:- xxx-xx-xxxx(entered my actual key here this is just for demo)
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

                  WARP-PLUS-CLOUDFLARE (script) By ALIILAPRO

[:(] Error when connecting to server.
[#] Total: 0 Good 0 Bad
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

![Screenshot 2020-05-30 at 8 46 35 AM](https://user-images.githubusercontent.com/61401662/83318412-30533980-a252-11ea-8107-47aaf17d90f6.png)

**Comment by ALIILAPRO** [comment]
> 
> 
> Last login: Sat May 30 08:34:45 on ttys000
> nimbus@MacBook-Pro ~ % python3 wp-plus.py
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't open file 'wp-plus.py': [Errno 2] No such file or directory
> nimbus@MacBook-Pro ~ % cd /Users/nimbus/Downloads/warp-plus-cloudflare-master
> nimbus@MacBook-Pro warp-plus-cloudflare-master % cd /Users/nimbus/Downloads/warp-plus-cloudflare-master
> nimbus@MacBook-Pro warp-plus-cloudflare-master % python3 wp-plus.py
> sh: -c: line 0: syntax error near unexpected token `(' sh: -c: line 0: `title WARP-PLUS-CLOUDFLARE By ALIILAPRO (version 3.0.0)'
> 
> ```
>   _______ _      __________________       _______ _______ _______ _______
>  (  ___  | \     \__   __|__   __( \     (  ___  |  ____ |  ____ |  ___  )
>  | (   ) | (        ) (     ) (  | (     | (   ) | (    )| (    )| (   ) |
>  | (___) | |        | |     | |  | |     | (___) | (____)| (____)| |   | |
>  |  ___  | |        | |     | |  | |     |  ___  |  _____)     __) |   | |
>  | (   ) | |        | |     | |  | |     | (   ) | (     | (\ (  | |   | |
>  | )   ( | (____/\__) (_____) (__| (____/\ )   ( | )     | ) \ \_| (___) |
>  |/     \(_______|_______|_______(_______//     \|/      |/   \__(_______)
> ```
> 
> ## [+] ABOUT SCRIPT:
> [-] With this script, you can getting unlimited GB on Warp+.
> [-] Version: 3.0.0
> ## [+] THIS SCRIPT CODDED BY ALIILAPRO
> [-] SITE: aliilapro.github.io
> [-] TELEGRAM: aliilapro
> 
> [#] Enter the WARP+ ID:- xxx-xx-xxxx(entered my actual key here this is just for demo)
> <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
> 
> ```
>               WARP-PLUS-CLOUDFLARE (script) By ALIILAPRO
> ```
> 
> [:(] Error when connecting to server.
> [#] Total: 0 Good 0 Bad
> <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
> 
> ![Screenshot 2020-05-30 at 8 46 35 AM](https://user-images.githubusercontent.com/61401662/83318412-30533980-a252-11ea-8107-47aaf17d90f6.png)

uninstall other version python, use python version 3.8.3.
